sudo: required
language: generic

services:
  - docker

#here we build the dev (test) image of react project
#andrzejcz below is dockerID
#build context (files) are taken frm ./client
before_install:
  - docker build -t andrzejcz/react-test -f ./client/dockerfile.dev ./client

#test run of image created above
script: 
  - docker run -e CI=true andrzejcz/react-test npm test



after_success: 
# after test are ok we build the PRD images
# we take default docker files fm context directories
  - docker build -t andrzejcz/multi-client ./client
  - docker build -t andrzejcz/multi-nginx ./nginx
  - docker build -t andrzejcz/multi-server ./server
  - docker build -t andrzejcz/multi-worker ./worker

# we want to push above images to dockerhub
#for this purpose 1st we log to docker cli
# as credentials are used environmental variables
#echo "$DOCKER_PASSWORD" takes password fm env. variablw and emits it on stdin to next command
#login -u : username login
#--password-stdin tells that we will receive passwor over stdin

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# after above login we push images to dockerhub 

  - docker push andrzejcz/multi-client 
  - docker push andrzejcz/multi-nginx
  - docker push andrzejcz/multi-server
  - docker push andrzejcz/multi-worker
#deployment to AWS EBS (entries below are thenEBS specific....)
deploy: 
  provider: elasticbeanstalk
  region: 'eu-central-1'
  #app: ESB application name (look at ESB dashboard)
  app: 'multi-docker'
  #env: ESB environment name
  env: 'MultiDocker-env'
  # S3 bucket is the location where Travis sizp the entire project
  # S3 buckets: this is S3 bucket associated with ESB (where ESB stores data)
  bucket_name: 'elasticbeanstalk-eu-central-1-364771153382'
  #bucket path was not explained; just has been called docker-multi
  bucket_path: 'docker-multi'
  #where to run the deployment
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    # secure: $AWS_SECRET_KEY


